# Compose file odoo huincan
# Version 2020-04-05

version: '3.5'

services:
  traefik:
    image: traefik:2.2.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --log.level=INFO
      - --log.format=json
      - --providers.docker
#      - --api.insecure
      - --certificatesresolvers.le.acme.email=jorge.obiols@gmail.com
      - --certificatesresolvers.le.acme.storage=/opt/traefik/acme.json
      - --certificatesresolvers.le.acme.httpChallenge=true
      - --certificatesresolvers.le.acme.httpChallenge.entryPoint=web
        # quitar esto para pasarlo a produccion
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "80:80"
#      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /odoo_ar/traefik/acme.json:/opt/traefik/acme.json

  pg-huincan:
    image: postgres:10.1-alpine
    container_name: pg-huincan
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - /odoo_ar/odoo-13.0e/huincan/postgresql/:/var/lib/postgresql/data

  sv-odoo:
    image: jobiols/odoo-ent:13.0e
    container_name: odoo-ee
    restart: unless-stopped
    volumes:
      - /odoo_ar/odoo-13.0e/huincan/config:/opt/odoo/etc/
      - /odoo_ar/odoo-13.0e/huincan/data_dir:/opt/odoo/data
      - /odoo_ar/odoo-13.0e/huincan/log:/var/log/odoo
      - /odoo_ar/odoo-13.0e/huincan/sources:/opt/odoo/custom-addons
      - /odoo_ar/odoo-13.0e/huincan/backup_dir:/var/odoo/backups/
    links:
      - pg-huincan:db
    environment:
      - SERVER_MODE=
      - ODOO_CONF=/dev/null

    labels:

      - traefik.http.routers.rou-odoo.rule=Host(`huincan.cumbre.net`)
      - traefik.http.routers.rou-odoo.entrypoints=web

      #- traefik.http.routers.rou-chat.rule=Host(`huincan.cumbre.net`) && PathPrefix(`/longpolling`)
      #- traefik.http.routers.rou-chat.entrypoints=web

      # comprime las paginas.
      - traefik.http.middlewares.compress.compress=true

      # redireccion http -> https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      - traefik.http.routers.rou-odoo.middlewares=redirect-to-https@docker
      - traefik.http.routers.rou-chat.middlewares=redirect-to-https@docker

      - traefik.http.routers.rou-odoo-secure.rule=Host(`huincan.cumbre.net`)
      - traefik.http.routers.rou-odoo-secure.tls=true
      - traefik.http.routers.rou-odoo-secure.tls.certresolver=le
      - traefik.http.routers.rou-odoo-secure.entrypoints=websecure

      # redirecciona al puerto 8069 de odoo
      - traefik.http.routers.rou-odoo-secure.service=srv-odoo-secure
      - traefik.http.services.srv-odoo-secure.loadbalancer.server.port=8069

#      - traefik.http.routers.rou-chat-secure.rule=Host(`huincan.cumbre.net`) && PathPrefix(`/longpolling`)
#      - traefik.http.routers.rou-chat-secure.tls=true
#      - traefik.http.routers.rou-chat-secure.tls.certresolver=le
#      - traefik.http.routers.rou-chat-secure.entrypoints=websecure
      # redirecciona al puerto 8072
#      - traefik.http.routers.rou-chat-secure.service=srv-chat-secure
#      - traefik.http.services.srv-chat-secure.loadbalancer.server.port=8072
